Hedgehog-Computing/hedgehog-lab

.github/workflows/nodejs.yml

refs: https://github.com/Himself65/hedgehog-lab/runs/838468273?check_suite_focus=true

ci: add build test

---

hedgehog-lab/package.json
hedgehog-lab/src/hedgehog_lab.js
hedgehog-lab/yarn.lock

preview image: https://wx2.sbimg.cn/2020/07/16/CUWJG.png

feat(style): redesign site using material-ui

---

hedgehog-lab/src/tutorials.ts

Reverts lidangzzz/hedgehog-lab#60

Revert "Update tutorials.ts"

---

CONTRIBUTING.md

Signed-off-by: imtsuki <me@qjx.app>

Update CONTRIBUTING.md to indicate dev branch is abandoned

---

package.json
patches/gpu.js+2.11.4.patch
yarn.lock

Fixes #89 
Upstreams https://github.com/gpujs/gpu.js/issues/711, https://github.com/stackgl/headless-gl/pull/215

fix(deps): gpu.js on macOS M1 chip

---

packages/hedgehog-lab/src/compiler.ts

https://user-images.githubusercontent.com/15878786/139787429-562a2e06-8909-4de7-a7dd-4a597c4122c0.mov

fix: memory leak

---

packages/hedgehog-lab/src/components/User/Auth/AuthForget/AuthForget.tsx
packages/hedgehog-lab/src/components/User/Auth/AuthForm/AuthFormSubmit.ts
packages/hedgehog-lab/src/components/User/Auth/AuthForm/AuthFormYup.ts
packages/hedgehog-lab/src/components/User/Auth/AuthForm/IAuthFormMethods.ts
packages/hedgehog-lab/src/components/User/Auth/AuthSign/AuthSign.tsx
packages/hedgehog-lab/src/config/route/route.tsx
packages/hedgehog-lab/src/pages/settings/Account.tsx

feat(setting): add account page

---

packages/hedgehog-lab/src/components/Layout/SideBar/SideBar.tsx
packages/hedgehog-lab/src/components/Snippet/Save/SaveState.tsx
packages/hedgehog-lab/src/components/YourCode/Header/YourCodeHeader.tsx
packages/hedgehog-lab/src/components/YourCode/YourCode.tsx
packages/hedgehog-lab/src/hooks/useCompilier.ts
packages/hedgehog-lab/src/hooks/useEditor.ts
packages/hedgehog-lab/src/pages/Main/Main.tsx
packages/hedgehog-lab/src/states/RYourCodeStates.ts

easy to use
```js
const [editorCode,
handleUploadSource,
handleEditorDidMount,
editor,
editorTheme,
options,
autoSaveCode
] = useEditor()
```

feat(Editor): create useEditor hook

---

packages/hedgehog-lab/src/components/Layout/Layout.tsx
packages/hedgehog-lab/src/components/Layout/SideBar/SideBar.tsx
packages/hedgehog-lab/src/components/Layout/TopBar/TopBar.tsx
packages/hedgehog-lab/src/components/Snippet/Save/SaveState.tsx
packages/hedgehog-lab/src/components/YourCode/Header/YourCodeHeader.tsx
packages/hedgehog-lab/src/components/YourCode/YourCode.tsx
packages/hedgehog-lab/src/hooks/useCompilier.ts
packages/hedgehog-lab/src/hooks/useEditor.ts
packages/hedgehog-lab/src/pages/Main/Main.tsx
packages/hedgehog-lab/src/states/RCompilerStates.ts

https://user-images.githubusercontent.com/13300332/159864555-250ef5bb-7e95-4842-80de-884fa56ae92a.mp4

feat: add live mode

---

packages/hedgehog-lab/src/components/Layout/SideBar/SideBar.tsx
packages/hedgehog-lab/src/components/Layout/TopBar/TopBar.tsx
packages/hedgehog-lab/src/components/YourCode/Header/YourCodeHeader.tsx

feat: add snippets collapse

---

packages/hedgehog-lab/src/components/Base/Popup/BasePopupText.tsx
packages/hedgehog-lab/src/components/Snippet/Save/SaveState.tsx

feat: add the file name editor box

---

packages/hedgehog-lab/src/App.tsx
packages/hedgehog-lab/src/components/Base/Popup/BasePopupButton.tsx
packages/hedgehog-lab/src/components/Layout/SideBar/SideBar.tsx
packages/hedgehog-lab/src/components/Share/SharePopup.tsx
packages/hedgehog-lab/src/components/Snippet/Delete/DeleteAlert.tsx
packages/hedgehog-lab/src/components/Snippet/Delete/DeletePopup.tsx
packages/hedgehog-lab/src/components/Snippet/Rename/RenameDialog.tsx
packages/hedgehog-lab/src/components/Snippet/Save/SaveState.tsx
packages/hedgehog-lab/src/hooks/useEditor.ts
packages/hedgehog-lab/src/pages/Snippets/Snippets.tsx

https://user-images.githubusercontent.com/13300332/160757281-2e56d267-89f3-4958-8800-066d211942d7.mp4

feat: add snippets version control

---

packages/hedgehog-lab/src/components/Layout/SideBar/SideBar.tsx

feat: add explore link

---

packages/hedgehog-lab/src/components/Share/SharePopup.tsx

https://user-images.githubusercontent.com/13300332/161171715-f8f2277d-985b-4f60-bb1d-c3408fcc2df3.mp4

feat: add multiple types of sharing tabs

---

packages/hedgehog-lab/package.json
packages/hedgehog-lab/src/models/useUser.ts
packages/hedgehog-lab/src/network/fetcher.ts
yarn.lock

https://swr.vercel.app/
https://github.com/prisma-labs/graphql-request

feat: add swr & graphql-request lib

---

package.json
packages/hedgehog-lab/src/App.tsx
packages/hedgehog-lab/src/components/Auth/Account/AccountMenu.tsx
packages/hedgehog-lab/src/components/Base/Input/Email/EmailInput.tsx
packages/hedgehog-lab/src/components/Base/Input/Password/PasswordInput.tsx
packages/hedgehog-lab/src/components/Layout/SideBar/SideBar.tsx
packages/hedgehog-lab/src/components/Layout/TopBar/TopBar.tsx
packages/hedgehog-lab/src/components/Snippet/List/SnippetList.tsx
packages/hedgehog-lab/src/components/YourCode/Header/YourCodeHeader.tsx
packages/hedgehog-lab/src/hooks/useAuth.tsx
packages/hedgehog-lab/src/interfaces/IFormInput.ts
packages/hedgehog-lab/src/pages/Auth/Auth.tsx
packages/hedgehog-lab/src/pages/Auth/Login.tsx
packages/hedgehog-lab/src/pages/Auth/Sign.tsx
packages/hedgehog-lab/src/pages/Main/Main.tsx
packages/hedgehog-lab/src/pages/Settings/Account.tsx
packages/hedgehog-lab/src/states/RAuthStates.ts

https://user-images.githubusercontent.com/13300332/162601305-2527cead-cfec-4e3f-a92b-0796d7735cf5.mp4

feat: add auth feature

---

docker/Dockerfile
docker/example_launch_linux.sh

Docker file based on debian for easier deployment
preferred entry: docker run -p 3000:3000 hedgehog-lab sh /opt/run.sh

add docker file

---

packages/hedgehog-core/src/transpiler/FetchURL/fetchApi.ts
packages/hedgehog-core/src/transpiler/preprocessor.ts

1. added *import @username/filename function to preprocessor.ts.
1.1 added a file fetchApi.ts to help to achieve this function.
2. changed some comments in preprocessor.ts.
2.1 mainly changed the subcomments of part 3.1.2 of function preprocessDFS().
3. fixed get the current file information part of function preprocessDFS() in preprocessor.ts. (3.1.2.1.2).

added *import @username/filename

---

packages/hedgehog-core/src/transpiler/FetchURL/fetchApi.ts

updated fetchApi to make it work under different hostname

updated fetchApi

---

packages/hedgehog-lab/src/pages/Auth/Sign.tsx

Update Sign Up button text
